title: Minsub Lee
url: "https://msublee.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

# footer: yes
# footer_url: "https://github.com/ankitsultana"
# footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
#  - name: "About"
  #  link: "/researcher/"
 - name: "CV"
   link: "CV.pdf"
#  - name: "Contact"
  #  link: "contact"
